# -*- coding: utf-8 -*-

# Copyright © 2010-2012 pygtk2exe Contributors
#
# This file is part of pygtk2exe.
#
# pygtk2exe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pygtk2exe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pygtk2exe. If not, see <http://www.gnu.org/licenses/>.


__all__ = ['Suite', 'Extension', 'CtypesComServer', 'ComServer', 'Service', 'Windows', 'Console', 'IsapiFilter']
__version__ = '0.0.1'


# Silence DeprecationWarnings generated by the py2exe 0.6.9 code
import warnings
warnings.filterwarnings(action='ignore',
                        message='the sets module is deprecated',
                        category=DeprecationWarning,
                        module='py2exe')

# Do a very strict py2exe version check to protect ourselves from the case
# where we should become incompatible with what future py2exe versions may expect.
from py2exe import __version__ as py2exe_version

if not py2exe_version == '0.6.9':
    raise ImportError('pygtk2exe requires py2exe 0.6.9 but found %s' % py2exe_version)

# Replace distutils.core.Distribution with our own Distribution class
import distutils
from pygtk2exe.dist import Distribution
distutils.core.Distribution = Distribution

# Make everything usable in setup.py scripts available
from pygtk2exe.targets import CtypesComServer, ComServer, Service, Windows, Console, IsapiFilter

# Keep our "namespace" clean
del warnings
del py2exe_version
del distutils
del Distribution
